JOB - PORTAL/Controllers/JobsController.cs
using JOB___PORTAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace JOB___PORTAL.Controllers
{
    public class JobsController : Controller
    {
        ProjectContext _db;
        public JobsController(ProjectContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            string email = HttpContext.Session.GetString("useremailID");
            if (email == null)
            {
                return RedirectToAction("Login", "Provider");
            }
            else
            {
                var jobslist = _db.tblJobs.Where(a => a.ProviderEmail == email).ToList();
                if (jobslist == null)
                {
                    ViewBag.Message = "No Record Found";
                }
                return View(jobslist);
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            //var jobslist = _db.tblJobs.ToList();
            //ViewBag.jobslist = jobslist;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Jobs obj)
        {
            try
            {
                obj.ProviderEmail = HttpContext.Session.GetString("useremailID");
                _db.tblJobs.Add(obj);
                _db.SaveChanges();
                TempData["Message"] = "Create Successful";
            }
            catch
            {
                TempData["Message"] = "Create unsuccessful";
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            try
            {
                var row =(from text  in _db.tblJobs where text.JobID == id select text).FirstOrDefault();
                _db.tblJobs.Remove(row);
                _db.SaveChanges();
                TempData["Message"] = "Deleted Succsessful";
            }
            catch
            {
                TempData["Message"] = "Deleted UnSuccessful";
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var row=(from text in _db.tblJobs where text.JobID==id select text).FirstOrDefault();
            return View(row);
        }
        [HttpPost]
        public IActionResult Edit(Jobs obj)
        {
            try
            {
                _db.Entry(obj).State=EntityState.Modified;
                _db.SaveChanges();
                TempData["Message"] = "Page Updated";
            }
            catch
            {
                TempData["Message"] = "Error occurd ";
            }
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            var row=(from text in _db.tblJobs where text.JobID==id select text).FirstOrDefault();
            return View(row);
        }
        public IActionResult ShowApplicant (int id)
        {
            //string SeekerEmail = HttpContext.Session.GetString("useremailID");
            var aplicantList=(from  t2 in _db.tblApply join t3 in _db.tblSeeker on
                              t2.JobSeekerEmail equals t3.Email where t2.JobID == id 
                              select new Seeker
                              {
                                  Email=t3.Email,
                                  Name=t3.Name,
                                  ContactInfo=t3.ContactInfo,
                               
                                  SeekerProfilePic=t3.SeekerProfilePic,
                                  SeekerCVFile=t3.SeekerCVFile,

                              }).ToList();
            return View(aplicantList);
        }
        public IActionResult ShowSeeker()
        {
            var seekerList=_db.tblSeeker.ToList();
            return View(seekerList);
        }
        public IActionResult Your_Profile()
        {
            string email = HttpContext.Session.GetString("useremailID");
            if (email == null)
            {
                TempData["Message"] = "Invalid";
                return RedirectToAction("Login");
            }
            else
            {
                var userprodier = _db.tblProvider.Where(a => a.Email == email).FirstOrDefault();
                return View(userprodier);
            }

        }
        [HttpGet]
        public IActionResult Edit_Profile()
        {
            string email = HttpContext.Session.GetString("useremailID");
            var row = _db.tblProvider.Where(a => a.Email == email).FirstOrDefault();
            return View(row);
        }
        [HttpPost]
        public IActionResult Edit_Profile(Provider obj)
        {
            try
            {
                _db.Entry(obj).State = EntityState.Modified;
                _db.SaveChanges();
                TempData["Message"] = "Updated Your Profile";
            }
            catch
            {
                TempData["Message"] = "Error Occured";
            }
            return RedirectToAction("Index");
        }
    }
}

JOB - PORTAL/Controllers/SeekerController.cs
using JOB___PORTAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using System.Security.Permissions;

namespace JOB___PORTAL.Controllers
{
    public class SeekerController : Controller
    {
        ProjectContext _db;
        IWebHostEnvironment _env;

        public SeekerController(ProjectContext db, IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }
        public IActionResult Index(string? searchText)
        {
            var Joblist = _db.tblJobs.Where(a => a.LastApplyDate > System.DateTime.Now).ToList();
            if (searchText != null)
            {
                Joblist = _db.tblJobs.Where(a => a.Company_Name.Contains(searchText) || a.SkillsRequired.Contains(searchText) ||
                a.Location.Contains(searchText)).ToList();
                ViewBag.SearchText = searchText;
                if (Joblist.Count == 0)
                {
                    ViewBag.Message = "No Record Found";
                }
            }
            return View(Joblist);
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(Seeker obj)
        {
            var LoginCheck = _db.tblSeeker.Where(a => a.Email == obj.Email && a.Password == obj.Password).FirstOrDefault();
            if (LoginCheck == null)
            {
                ViewBag.Message = "Enter Your Currect Email ID & Passward";
                return View();
            }
            else
            {
                HttpContext.Session.SetString("useremailID", obj.Email);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Your_Profile()
        {
            string email = HttpContext.Session.GetString("useremailID");
            if (email == null)
            {
                TempData["Message"] = "Invalid";
                return View("Login");
            }
            else
            {
                var userseeker = _db.tblSeeker.Where(a => a.Email == email).FirstOrDefault();
                return View(userseeker);
            }
        }
        [HttpGet]
        public IActionResult Registration()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Registration(Seeker obj)
        {
            try
            {
                var useremailcheck = _db.tblSeeker.Where(a => a.Email == obj.Email).FirstOrDefault();
                if (useremailcheck != null)
                {
                    TempData["Message"] = "Email already exists. Please use a different email.";
                    return View(obj);
                }
                else
                {
                    if (obj.SeekerProfilePicPath != null)
                    {
                        obj.SeekerProfilePic = UploadSeekerProfilePic(obj.SeekerProfilePicPath);
                    }
                    if (obj.SeekerCVFilePath != null)
                    {
                        obj.SeekerCVFile = UploadSeekerCVfilepath(obj.SeekerCVFilePath);
                    }

                }
                _db.tblSeeker.Add(obj);
                _db.SaveChanges();
                TempData["Message"] = "Registration Succsess";

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
            return RedirectToAction("Login");
        }
        string UploadSeekerProfilePic(IFormFile profilepic)
        {
            string filename = "";
            string path = Path.Combine(_env.WebRootPath, "SeekerProfilePic");
            filename = Guid.NewGuid().ToString().Substring(0, 1) + "_" + profilepic.FileName;
            string filepath = Path.Combine(path, filename);
            using (var filestream = new FileStream(filepath, FileMode.Create))
            {
                profilepic.CopyTo(filestream);
            }
            return filename;
        }
        string UploadSeekerCVfilepath(IFormFile CVfilepath)
        {
            string filename = "";
            string path = Path.Combine(_env.WebRootPath, "SeekerCVFile");
            filename = Guid.NewGuid().ToString().Substring(0, 1) + "_" + CVfilepath.FileName;
            string filePath = Path.Combine(path, filename);
            using (var filestream = new FileStream(filePath, FileMode.Create))
            {
                CVfilepath.CopyTo(filestream);
            }
            return filename;
        }

        public IActionResult Show_Jobs()
        {

            var jobslist = _db.tblJobs.Where(a => a.LastApplyDate > System.DateTime.Now).ToList();
            return View(jobslist);
        }
        public IActionResult Apply(int id)
        {
            try
            {
                string SeekerEmail = HttpContext.Session.GetString("useremailID");
                var Applied = _db.tblApply.Where(a => a.JobID == id && a.JobSeekerEmail == SeekerEmail).FirstOrDefault();
                if (Applied == null)
                {
                    Apply obj = new Apply();
                    obj.JobID = id;
                    obj.JobSeekerEmail = SeekerEmail;

                    obj.AppliedDate = System.DateTime.Now;
                    _db.tblApply.Add(obj);
                    _db.SaveChanges();
                    TempData["Message"] = "Applied Succsessful";

                }
                else
                {
                    TempData["Message"] = "Already Applied This Job Post";
                }
            }
            catch
            {
                TempData["Message"] = "Some error Occured";
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit()
        {
            string email = HttpContext.Session.GetString("useremailID");
            var row = _db.tblSeeker.Where(a => a.Email == email).FirstOrDefault();
            return View(row);
        }
        [HttpPost]
        public IActionResult Edit(Seeker obj)
        {
            try
            {
                _db.Entry(obj).State = EntityState.Modified;
                _db.SaveChanges();
                TempData["Message"] = "Updated Your Profile";
            }
            catch
            {
                TempData["Message"] = "Error Occured";
            }
            return RedirectToAction("Index");
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
             
        }
        
    }
}

JOB - PORTAL/Views/Shared/_Layout.cshtml
@* @using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor
 *@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JOB___PORTAL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JOB___PORTAL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" class="" asp-area="" asp-controller="Home" asp-action="Index">JOB___PORTAL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="btn btn-outline-info" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-secondary" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-success" asp-area="" asp-controller="Seeker" asp-action="Login">Seeker</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-primary" asp-area="" asp-controller="Provider" asp-action="Login">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-warning" asp-area="" asp-controller="Home" asp-action="Terms_Condition">Terms & Condition</a>
                        </li>
                      @*   @if (Accessor.HttpContext.Session.GetString("useremailID") != null)
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-danger" asp-area="" asp-controller="Provider" asp-action="Logout">Logout</a>
                            </li>
                        }
                        @if (Accessor.HttpContext.Session.GetString("useremailID") != null)
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-danger" asp-area="" asp-controller="Seeker" asp-action="Logout">Logout</a>
                            </li>
                        } *@
                       @*    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="Index">Show_Jobs</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;Dibakar Ghosh 2025 - JOB___PORTAL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>